var data = [
  {
    id : 0,
    crimes : "Conspiracy to import and possess with intent to deliver cocaine; Possession with intent to deliver cocaine; Money laundering; Racketeering influenced and corrupt organizations (rico) - Drug trafficking; Conspiracy to distribute or manufacture cocaine abroad with knowledge or intent that it be imported into the United States",
    name : "Diego Leon Montoya Sanchez",
    link : "http://www.fbi.gov/wanted/topten/fugitives/montoya.htm",
    photos : [{url:"http://www.fbi.gov/wanted/topten/fugitives/montoya.jpg",
               info:""} ],
    aliases : ["Diego Montoya", "Diego Sanchez-Montoya", "%22Don Diego%22", "%22El Senor De La Guerra%22", "%22El Ciclista%22"],
    description : {
      "Dates of Birth Used" : ["January 11, 1958", "January 11, 1961"],
      "Hair" : "Black",
      "Place of Birth" : "Trujillo, Colombia",
      "Eyes" : "Brown",
      "Height" : "6%270%22",
      "Complexion" : "Medium",
      "Weight" : "230 pounds",
      "Sex" : "Male",
      "Build" : "Heavy",
      "Race" : "White (Hispanic)",
      "Occupation" : "Rancher",
      "Nationality" : "Colombian",
      "Scars and Marks" : "Montoya has surgical scars on his lower back and legs due to injuries sustained in an automobile accident.",
      "Remarks" : "Montoya is presently protected by the Colombian paramilitary group, %22Autodefensas Unidas de Colombia%22 (AUC).",
      "Threat" : "Considered armed and extremely dangerous"
    },
    caution : "Diego Leon Montoya Sanchez is being sought in connection with the manufacture and distribution of multiple tons of cocaine, knowing or intending that it will be imported into the United States. Montoya is reputedly one of the principal leaders of the Colombian north valley drug cartel. The north valley cartel is believed to be the most powerful and violent drug trafficking organization in Colombia. The cartel reportedly relies heavily for protection on illegal armed groups, taking help from right-wing paramilitaries as well as leftist rebels.",
    contact : "If you have any information concerning this person, please contact your local FBI office or the nearest U.S. embassy or consulate.",
    rewardAmount : 5000000,
    reward : "The United States Department of State Narcotics Rewards Program is offering a reward of up to $5 million for information leading directly to the arrest or conviction of Diego Leon Montoya Sanchez.",
    dates : ["May 2004"]
  },
  {
    id : 1,
    crimes : "Racketeering influenced and corrupt organizations (rico) - Murder (18 counts), Conspiracy to commit murder, conspiracy to commit extortion, narcotics distribution, conspiracy to commit money laundering; Extortion; Money laundering",
    name : "James J. Bulger",
    link : "http://www.fbi.gov/wanted/topten/fugitives/bulger.htm",
    photos : [ {url:"http://www.fbi.gov/wanted/topten/fugitives/bulger1.jpg",
                info:"Photograph taken in 1994"},
               {url:"http://www.fbi.gov/wanted/topten/fugitives/bulger2.jpg",
                info:"Photograph taken in 1994"},
               {url:"http://www.fbi.gov/wanted/topten/fugitives/bulger3.jpg",
                info:"Photograph altered in 2000"} ],
    aliases : ["Thomas F. Baxter", "Mark Shapeton", "Jimmy Bulger", "James Joseph Bulger", "James J. Bulger, Jr.", "James Joseph Bulger, Jr.", "Tom Harris", "Tom Marshall", "%22Whitey%22"],
    description : {
      "Date of Birth" : ["September 3, 1929"],
      "Hair" : "White/Silver",
      "Place of Birth" : "Boston, Massachusetts",
      "Eyes" : "Blue",
      "Height" : "5%277%22 to 5%279%22",
      "Complexion" : "Light",
      "Weight" : "150 to 160 pounds",
      "Sex" : "Male",
      "Build" : "Medium",
      "Race" : "White",
      "Occupation" : "Unknown",
      "Nationality" : "American",
      "Scars and Marks" : "None known",
      "Remarks" : "Bulger is an avid reader with an interest in history. He is known to frequent libraries and historic sites. Bulger is currently on the heart medication Atenolol (50 mg) and maintains his physical fitness by walking on beaches and in parks with his female companion, Catherine Elizabeth Greig. Bulger and Greig love animals and may frequent animal shelters. Bulger has been known to alter his appearance through the use of disguises. He has traveled extensively throughout the United States, Europe, Canada, and Mexico.",
      "Threat" : "Considered armed and extremely dangerous"
    },
    caution : "James J. Bulger is being sought for his role in numerous murders committed from the early 1970s through the mid-1980s in connection with his leadership of an organized crime group that allegedly controlled extortion, drug deals, and other illegal activities in the Boston, Massachusetts, area. He has a violent temper and is known to carry a knife at all times.",
    contact : "If you have any information concerning this person, please contact your local FBI office or the nearest U.S. embassy or consulate.",
    rewardAmount : 1000000,
    reward : "The FBI is offering a $1,000,000 reward for information leading directly to the arrest of James J. Bulger.",
    dates : ["August 1999", "November 2000"]
  },
  {
    id : 2,
    crimes : "Sexual exploitation of children (production of child pornography); Unlawful flight to avoid prosecution - Lewd acts upon a child (six counts), Possession of child pornography (two counts)",
    name : "Richard Steve Goldberg",
    link : "http://www.fbi.gov/wanted/topten/fugitives/goldberg.htm",
    photos : [{url:"http://www.fbi.gov/wanted/topten/fugitives/goldberg1.jpg",
               info:"Photograph taken in 2001"},
              {url:"http://www.fbi.gov/wanted/topten/fugitives/goldberg2.jpg",
               info:"Photograph taken in 2001"} ],
    aliases : ["Richard Goldberg", "Richard S. Goldberg"],
    description : {
      "Date of Birth" : "November 9, 1945",
      "Hair" : "Black",
      "Place of Birth" : "Brooklyn, New York",
      "Eyes" : "Brown",
      "Height" : "6%270%22",
      "Complexion" : "Medium",
      "Weight" : "160 pounds",
      "Sex" : "Male",
      "Build" : "Medium",
      "Race" : "White",
      "Occupation" : "Former Engineer",
      "Nationality" : "American",
      "Scars and Marks" : "None known",
      "Remarks" : "Goldberg has a thick moustache and a receding hairline. He was the president of a gun club in Long Beach, California. Goldberg has ties to, or may have traveled to, New Jersey, Nevada, Colorado, Arizona, and Georgia.",
      "Threat" : "Considered armed and dangerous"
    },
    caution : "Richard Steve Goldberg is wanted for allegedly engaging in sexual activities with several female children under the age of ten in Long Beach, California, from January through May of 2001. He also allegedly produced images of these sex acts which were later found on his computer.",
    contact : "If you have any information concerning this person, please contact your local FBI office or the nearest U.S. embassy or consulate.",
    rewardAmount : 100000,
    reward : "The FBI is offering a reward of up to $100,000 for information leading directly to the arrest of Richard Steve Goldberg.",
    dates : ["June 2002", "January 2005"]
  },

  {
    id : 3,
    crimes : "Unlawful flight to avoid prosecution - murder",
    name : "Jorge Alberto Lopez-Orozco",
    link : "http://www.fbi.gov/wanted/topten/fugitives/lopez-orozco.htm",
    photos : [{url:"http://www.fbi.gov/wanted/topten/fugitives/lopez-orozco1.jpg",
               info:""},
              {url:"http://www.fbi.gov/wanted/topten/fugitives/lopez-orozco2.jpg",
               info:""},
              {url:"http://www.fbi.gov/wanted/topten/fugitives/lopez-orozco3.jpg",
               info:""} ],
    aliases : ["Raul Solario", "Raul Solorio", "Jorge Orozco-Lopez", "Jorge Alberto Orozco-Lopez", "%22Pepe%22"],
    description : {
      "Date of Birth" : "April 22, 1976",
      "Hair" : "Black",
      "Place of Birth": "Mexico",
      "Eyes" : "Brown",
      "Height" : "5%277%22",
      "Complexion" : "Dark",
      "Weight" : "175 pounds",
      "Sex" : "Male",
      "Build" : "Medium",
      "Race" : "White (Hispanic)",
      "Occupation(s)": "Unknown",
      "Nationality" : "Mexican",
      "Scars and Marks" : "None known",
      "Remarks" : "Lopez-Orozco has ties to San Jose, California; Idaho, and Mexico. He may have fled to Michoacan, Mexico. Lopez-Orozco may be traveling with his brother, Simon Lopez-Orozco and Simon's wife, Maria Garcia, who have both been charged with accessory to first degree murder.",
      "Threat" : "Considered armed and extremely dangerous."
    },
    caution : "Jorge Alberto Lopez-Orozco is wanted for allegedly shooting to death three people in Elmore County, Idaho. The charred remains of a woman and her two young sons, aged two and four, were found inside a burned out vehicle on August 11, 2002. Each victim was shot in either the head or the chest.",
    contact : "If you have any information concerning this person, please contact your local FBI office or the nearest U.S. embassy or consulate.",
    rewardAmount : 100000,
    reward : "The FBI is offering a reward of up to $100,000 for information leading directly to the arrest of Jorge Alberto Lopez-Orozco.",
    dates : ["March 2005"]
  },
  {
    id : 4,
    crimes : "Murder of U.S. nationals outside the United States; conspiracy to murder U.S. nationals outside the United States; Attack on a federal facility resulting in death",
    name : "Usama Bin Laden",
    link : "http://www.fbi.gov/wanted/topten/fugitives/laden.htm",
    photos : [{url:"http://www.fbi.gov/wanted/topten/fugitives/laden.jpg",
               info:"Date of Photograph Unknown"}],
    aliases : ["Usama Bin Muhammad Bin Ladin", "Shaykh Usama Bin Ladin", "the Prince", "the Emir", "Abu Abdallah", "Mujahid Shaykh", "Hajj", "the Director"],
    description : {
      "Date of Birth" : "1957",
      "Hair" : "Brown",
      "Place of Birth" : "Saudi Arabia",
      "Eyes" : "Brown",
      "Height" : "6%27 4%22 to 6%27 6%22",
      "Complexion" : "Olive",
      "Weight" : "Approximately 160 pounds",
      "Sex" : "Male",
      "Build" : "Thin",
      "Nationality" : "Saudi Arabian",
      "Occupation" : "Unknown",
      "Remarks" : "Bin Laden is the leader of a terrorist organization known as Al-Qaeda, %22The Base%22. He is left-handed and walks with a cane.",
      "Scars and Marks": "None",
      "Threat" : "considered armed and extremely dangerous"
    },
    caution : "Usama Bin Laden is wanted in connection with the August 7, 1998, bombings of the United States Embassies in Ear Es Salaam, Tanzania, and Nairobi, Kenya. These attacks killed over 200 people. In addition, Bin Laden is a suspect in other terrorist attacks throughout the world.",
    contact : "If you have any information concerning this person, please contact your local FBI office or the nearest U.S. embassy or consulate.",
    rewardAmount : 27000000,
    reward : "The Rewards For Justice Program, United States Department of State, is offering a reward of up to $25 million for information leading directly to the apprehension or conviction of Usama Bin Laden. An additional $2 million is being offered through a program developed and funded by the Airline Pilots Association and the Air Transport Association.",
    dates : ["June 1999", "November 2001"]
  },
  {
    id : 5,
    crimes : "Unlawful flight to avoid prosecution - First degree murder (3 counts), Arson of an occupied structure",
    name : "Robert William Fisher",
    link : "http://www.fbi.gov/wanted/topten/fugitives/fisher.htm",
    photos : [{url:"http://www.fbi.gov/wanted/topten/fugitives/fisher1bw.jpg",
               info:"Photograph taken in 1999"},
              {url:"http://www.fbi.gov/wanted/topten/fugitives/fisher2bw.jpg",
               info:"Photograph taken in 1997"},
              {url:"http://www.fbi.gov/wanted/topten/fugitives/fisher5bw.jpg",
               info:""} ],
    aliases: ["Robert W. Fisher"],
    description : {
      "Date of Birth" : "April 13, 1961",
      "Hair" : "Brown",
      "Place of Birth" : "Brooklyn, New York",
      "Eyes" : "Blue",
      "Height" : "6%270%22",
      "Complexion" : "Light",
      "Weight" : "190 pounds",
      "Sex" : "Male",
      "Build" : "Medium",
      "Race" : "White",
      "Occupations" : "Surgical Catheter Technician, Respiratory Therapist, Fireman",
      "Nationality" : "American",
      "Scars and Marks" : "Fisher has surgical scars on his lower back.",
      "Remarks" : "Fisher is physically fit and is an avid outdoorsman, hunter, and fisherman. He has a noticeable gold crown on his upper left first bicuspid tooth. He may walk with an exaggerated erect posture and his chest pushed out due to a lower back injury. Fisher is known to chew tobacco heavily. He has ties to New Mexico and Florida. Fisher is believed to be in possession of several weapons, including a high-powered rifle.",
      "Threat" : "Considered armed and extremely dangerous"
    },
    caution : "Robert William Fisher is wanted for allegedly killing his wife and two young children and then blowing up the house in which they all lived in Scottsdale, Arizona in April of 2001.",
    contact : "If you have any information concerning this person, please contact your local FBI office or the nearest U.S. embassy or consulate.",
    rewardAmount : 100000,
    reward : "The FBI is offering a reward of up to $100,000 for information leading directly to the arrest of Robert William Fisher.",
    dates : ["June 2002", "January 2005"]
  },
  {
    id : 6,
    crimes : "Unlawful flight to avoid prosecution - Attempted murder of a police officer, Assault with a deadly weapon, Parole violation",
    name : "Emigdio Preciado Jr.",
    link : "http://www.fbi.gov/wanted/topten/fugitives/preciado_e.htm",
    photos : [{url:"http://www.fbi.gov/wanted/topten/fugitives/preciado_e1.jpg",
               info:""},
              {url:"http://www.fbi.gov/wanted/topten/fugitives/preciado_e2.jpg",
               info:""},
              {url:"http://www.fbi.gov/wanted/topten/fugitives/preciado_e3.jpg",
               info:""} ],
    aliases : ['Emigdio Prceiado', 'Emigdio Preciado', 'Junior Preciado', 'Emigdio Precido', 'Enigdio Preciado', 'Enigdio Preciado Jr.', 'Enigdio Preciado', 'Jr.', 'Emigdio Preciado J R', 'Emigdio Priciado Jr.', '"Junior," Jr. Preciado', '"Trigger," "Spooky," Spooky Preciado', '"Snyper"'],
    description : {
      "Date of Birth" : "August 19, 1969; August 19, 1968; September 19, 1969",
      "Hair" : "Brown",
      "Place of Birth" : "California",
      "Eyes" : "Brown",
      "Height" : "5%275%22",
      "Complexion" : "Medium",
      "Weight" : "180 pounds",
      "Sex" : "Male",
      "Build" : "Medium",
      "Race" : "White (Hispanic)",
      "Occupation" : "Construction; Involvement in vehicle tire business",
      "Nationality" : "American",
      "Scars and Marks" : "Preciado has a horizontal scar on his left ear, a black mole below his right eye, and tattoos of the words 'Susana' and 'Alexa' on his left chest. He may have had plastic surgery to remove the scars and tattoos.",
      "Remarks" : "Preciado is a known member of a violent street gang in Los Angeles, California. He is believed to be in Mexico.",
      "Threat" : "Considered armed and extremely dangerous."
    },
    caution : "Emigdio Preciado Jr. is wanted for an attack on two Los Angeles County Sheriff's Department deputies on September 5, 2000, in Whittier, California, during a routine traffic stop. Preciado fired twenty-one rounds from an assault rifle, striking one of the deputies in the head.",
    contact : "If you have any information concerning this person, please contact your local FBI office or the nearest U.S. embassy or consulate.",
    rewardAmount : 100000,
    reward : "The FBI is offering a reward of up to $100,000 for information leading directly to the arrest of Emigdio Preciado Jr.",
    dates : ["March 2007"]
  },
  {
    id : 7,
    crimes : "Bank robbery; Unlawful flight to avoid prosecution - Armed robbery; Theft from interstate shipment",
    name : "Victor Manuel Gerena",
    link : "http://www.fbi.gov/wanted/topten/fugitives/gerena.htm",
    photos : [{url:"http://www.fbi.gov/wanted/topten/fugitives/gerena1.jpg",
               info:"Photograph taken in 1983"},
              {url:"http://www.fbi.gov/wanted/topten/fugitives/gerena2.jpg",
               info:"Photograph retouched in 2004"},
              {url:"http://www.fbi.gov/wanted/topten/fugitives/gerenaage.jpg",
               info:"Computer Age Enhanced Photograph"} ],
    aliases : ["Victor Ortiz", "Victor M. Gerena Ortiz"],
    description : {
      "Date of Birth" : "June 24, 1958",
      "Hair" : "Brown",
      "Place of Birth" : "New York, New York",
      "Eyes" : "Green",
      "Height" : "5%276%22 to 5%277%22",
      "Complexion" : "Dark/Medium",
      "Weight" : "160 to 169 pounds",
      "Sex" : "Male",
      "Build" : "Medium/Stocky",
      "Race" : "White (Hispanic)",
      "Occupations" : "Machinist, security guard",
      "Nationality" : "American (Puerto Rican descent)",
      "Scars and Marks" : "Gerena has a one-inch scar and a mole on his right shoulder blade.",
      "Remarks" : "None",
      "Threat" : "Considered armed and extremely dangerous."
    },
    caution : "Victor Manuel Gerena is being sought in connection with the armed robbery of approximately $7 million from a security company in Connecticut in 1983. He allegedly took two security employees hostage at gunpoint and then handcuffed, bound and injected them with an unknown substance in order to further disable them.",
    contact : "If you have any information concerning this person, please contact your local FBI office or the nearest U.S. embassy or consulate.",
    rewardAmount : 1000000,
    reward : "The FBI is offering a reward of up to one million dollars for information leading directly to the arrest of Victor Manuel Gerena.",
    dates : ["May 1984", "December 2004"]
  },
  {
    id : 8,
    crimes : "Unlawful flight to avoid confinement - Murder, escape",
    name : "Glen Stewart Godwin",
    link : "http://www.fbi.gov/wanted/topten/fugitives/godwin.htm",
    photos : [{url:"http://www.fbi.gov/wanted/topten/fugitives/godwin.jpg",
               info:"Photograph taken in 1991"},
              {url:"http://www.fbi.gov/wanted/topten/fugitives/godwin3.jpg",
               info:"Photograph taken in 1991"},
              {url:"http://www.fbi.gov/wanted/topten/fugitives/godwinaged.jpg",
               info:"Age enhanced photograph"} ],
    aliases : ["Michael Carrera", "Miguel Carrera", "Michael Carmen", "Glen Godwin", "Glen S. Godwin", "Dennis H. McWilliams", "Dennis Harold McWilliams"],
    description : {
      "Date of Birth": "June 26, 1958",
      "Hair" : "Black/Salt and Pepper",
      "Place of Birth" : "Miami, Florida",
      "Eyes" : "Green",
      "Height" : "6%270%22",
      "Complexion" : "Medium to Dark",
      "Weight" : "200 pounds",
      "Sex" : "Male",
      "Build" : "Medium",
      "Race" : "White",
      "Occupations" : "Self-employed in tool supplies, mechanic, construction worker",
      "Nationality" : "American",
      "Scars and Marks" : "None known",
      "Remarks" : "Godwin is fluent in Spanish and may be traveling throughout Central and South America, and Mexico. He is thought to be involved in narcotics distribution.",
      "Threat" : "Considered armed and extremely dangerous and an escape risk."
    },
    caution : "Glen Stewart Godwin is being sought for his 1987 escape from Folsom State Prison in California, where he was serving a lengthy sentence for murder. Later in 1987, Godwin was arrested for drug trafficking in Puerta Vallarta, Mexico. After being convicted, he was sent to a prison in Guadalajara. In April of 1991, Godwin allegedly murdered a fellow inmate and then escaped five months later.",
    contact : "If you have any information concerning this person, please contact your local FBI office or the nearest U.S. embassy or consulate.",
    rewardAmount : 100000,
    reward : "The FBI is offering a reward of up to $100,000 for information leading directly to the arrest of Glen Stewart Godwin.",
    dates : ["December 1996", "January 2005"]
  },
  {
    id : 9,
    crimes : "Unlawful flight to avoid prosecution - Kidnapping, Murder",
    name : "Alexis Flores",
    link : "http://www.fbi.gov/wanted/topten/fugitives/flores_a.htm",
    photos : [{url:"http://www.fbi.gov/wanted/topten/fugitives/flores_a_bw.jpg",
               info:"Photograph taken in 2005"},
              {url:"http://www.fbi.gov/wanted/topten/fugitives/flores_a2.jpg",
               info:"Photograph taken in 2002"} ],
    aliases : ["Mario Flores", "Mario Roberto Flores", "Mario F. Roberto", "Alex Contreras", "Alesis Contreras"],
    description : {
      "Date of Birth" : "July 18, 1975; July 18, 1982; September 15, 1980; July 17, 1982",
      "Hair" : "Black",
      "Place of Birth" : "Honduras",
      "Eyes" : "Brown",
      "Height" : "5%274%22",
      "Complexion" : "Light",
      "Weight" : "130 to 140 pounds",
      "Sex" : "Male",
      "Build" : "Slim",
      "Race" : "White (Hispanic)",
      "Occupations" : "Handyman",
      "Nationality" : "Honduran",
      "Scars and Marks" : "Flores has scars on his forehead and right cheek.",
      "Remarks" : "Flores has ties to Honduras.",
      "Threat" : "Considered armed and extremely dangerous and an escape risk."
    },
    caution : "Alexis Flores is wanted for his alleged involvement in the kidnapping and murder of a five-year-old girl in Philadelphia, Pennsylvania. The girl was reported missing in late July of 2000, and later found strangled to death in a nearby apartment in early August of 2000.",
    contact : "If you have any information concerning this person, please contact your local FBI office or the nearest U.S. embassy or consulate.",
    rewardAmount : 100000,
    reward : "The FBI is offering a reward of up to $100,000 for information leading directly to the arrest of Alexis Flores.",
    dates : ["May 2007"]
  }
];
